/*
*Copyright(C)2015NikhilAP
*
*Thisprogramisfreesoftware:youcanredistributeitand/ormodify
*itunderthetermsoftheGNUGeneralPublicLicenseaspublishedby
*theFreeSoftwareFoundation,eitherversion3oftheLicense,or
*(atyouroption)anylaterversion.
*
*Thisprogramisdistributedinthehopethatitwillbeuseful,
*butWITHOUTANYWARRANTY;withouteventheimpliedwarrantyof
*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.Seethe
*GNUGeneralPublicLicenseformoredetails.
*
*YoushouldhavereceivedacopyoftheGNUGeneralPublicLicense
*alongwiththisprogram.Ifnot,see<http://www.gnu.org/licenses/>.
*/

#ifndef__HTTP_STATS_H
#define__HTTP_STATS_H

typedefstructhttp_stats_connection_s{
structtimespecrequest_transfer_time;
structtimespecconn_run_time;

uint8_thttp_transfer_error:1,
http_internal_error:1,
http_code_unused:6;

uint32_thttp_code_1xx;
uint32_thttp_code_2xx;
uint32_thttp_code_3xx;
uint32_thttp_code_4xx;
uint32_thttp_code_5xx;

/*Thetotaltimeinsecondsforthetransfer*/
doubletotal_transfer_time;
doubletotal_connection_time;

/*Totalamountofbytesthatwereuploaded.*/
doubleuploaded_bytes;

/*Averageuploadspeedinbytes/second*/
doubleupload_speed;

/*Totalamountofbytesthatweredownloadedforlasttransfer.*/
doubledownloaded_bytes;

/*Averageuploadspeedinbytes/second*/
doubledownload_speed;

uint32_ttotal_requests_sent;
uint32_ttotal_responses_received;
}http_stats_connection_t;

typedefhttp_stats_connection_thttp_stats_request_t;

typedefstructhttp_stats_request_table_s{
uint32_ttotal_requests;
uint32_tcurrent_request;
http_stats_request_trequest_table[1];
}http_stats_request_table_t;

typedefstructhttp_stats_base_s{

/*Timerelatedstats*/
structtimespecrun_time;
doubletotal_run_time;

/*Totalstats*/
uint32_ttotal_running_connections;
uint32_ttotal_completed_connections;
uint32_ttotal_requests_sent;
uint32_ttotal_responses_received;
uint32_ttotal_errors;
uint32_ttotal_successful_connects;
uint32_ttotal_failed_connects;
uint32_ttotal_failed_connections;
uint32_ttotal_uploaded_bytes;
uint32_ttotal_downloaded_bytes;
uint32_ttotal_http_code_1xx;
uint32_ttotal_http_code_2xx;
uint32_ttotal_http_code_3xx;
uint32_ttotal_http_code_4xx;
uint32_ttotal_http_code_5xx;

/*Averagestatsforsuccessfulconnections*/
doubleaverage_transfer_time;
doubleaverage_upload_speed;
doubleaverage_download_speed;
doubleaverage_requests_sent_in_a_second;
doubleaverage_responses_received_in_a_second;

/*Currentstats*/
uint32_trequests_sent_in_a_second;
uint32_tresponses_received_in_a_second;

/*Percentiles*/
doublerequest_percentile_95;

http_stats_request_table_t*requests_stat_table;

}http_stats_base_t;

voidhttp_stats_calculate_average(double*curr_average,
doublenew_value,uint32_ttotal);

http_stats_request_table_t*http_stats_init_request_table(uint32_ttotal_requests);
voidhttp_stats_calculate_request_percentile(void*data);
voidhttp_stats_update_engine_stats(http_stats_base_t*engine_stats,
http_stats_base_t*worker_stats,intworkers);
#endif/*__HTTP_STATS_H*/
